---
output: html_document
---

```{r, echo=FALSE, warning=FALSE}
library(ggplot2)
library(leaflet)
library(knitr)
library(lubridate)
```

# `r zones@data[i,3] ` Air Quality Factsheet

## Boundary of `r zones@data[i,3]` & AQMA zones

```{r Boundary Area Map, echo=FALSE}

if(length(AQMA[zones[i,],]) >= 1){
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
addPolygons(
    data=zones[i,], fillOpacity = 0, weight = 2) %>%
addPolygons(
  data=AQMA[zones[i,],], color = "red", weight = 1)
} else {
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
addPolygons(
    data=zones[i,], fillOpacity = 0, weight = 2)
  print("There are no AQMA zones in this area")
}

```

© Ordnance Survey & Crown copyright and database right 2017
[add in AQMA shp file copyright notice]

## Boundary of `r zones@data[i,3]` & AURN stations

```{r Boundary Area Map 2, echo=FALSE}

if(length(AQMA[zones[i,],]) >= 1){
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
addPolygons(
    data=zones[i,], fillOpacity = 0, weight = 2) %>%
addCircleMarkers(
  data=stations_raw[zones[i,],], color = "red", weight = 1)
} else {
  print("There are no AURN stations in this area")
}

```

© Ordnance Survey & Crown copyright and database right 2017
[add in AURN points copyright notice]

## NOx



```{r}
if(!is.null(nox)){
  #plot(nox$date, nox$nox)
  nox$day <- weekdays(as.Date(nox$date))
  nox$month <- months(as.Date(nox$date))
  
  nox$month<-as.ordered(nox$month) 
  
  ggplot(data = nox, aes(x = day, y=nox)) + geom_boxplot()
  ggplot(data = nox, aes(x = month, y=nox)) + geom_boxplot()
  
} else {
  print("No NOx measures")
}
```

 
```{r Accident location subset, fig.width=8, fig.height=10, echo=FALSE, warning=FALSE, message=FALSE}

# 
# LAmap2 <-leaflet() %>%
#   addTiles() %>% # Add default OpenStreetMap map tiles
#   addPolygons(
#     data=LA.subset, fillOpacity = 0.1, weight = 2) %>%
# addCircleMarkers(
#     data = airquality_subset,
#     radius = 1, color="blue")
# 
# LAmap2  # Print the map

```

```{r}

# df <- get1Hdata('MY1', years=2015)
# 
# # Aggregate to daily means and plot
# library('zoo')
# par(mai = c(0.5, 1, 0, 0)) 
# my1 <- zoo(x = df$Ozone, order.by = as.POSIXlt(df$datetime))
# plot(aggregate(my1, as.Date(as.POSIXlt(df$datetime)), mean), 
#      main = '', xlab = '', ylab = expression(paste('Ozone concentration [',
#                                                     mu, 'g/', m^3, ']')))
```